package org.locoad.db.entities.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;
import org.locoad.db.entities.Dbstatus;
import org.locoad.db.entities.Formflow;
import org.locoad.db.entities.StateTransition;

/**
 * Class _Dbrole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Dbrole extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ROLE_ID_PK_COLUMN = "role_id";

    public static final Property<String> ROLE_NAME = Property.create("roleName", String.class);
    public static final Property<List<Dbstatus>> DBSTATUSES = Property.create("dbstatuses", List.class);
    public static final Property<Formflow> FF = Property.create("ff", Formflow.class);
    public static final Property<List<StateTransition>> STATE_TRANSITIONS = Property.create("stateTransitions", List.class);

    protected String roleName;

    protected Object dbstatuses;
    protected Object ff;
    protected Object stateTransitions;

    public void setRoleName(String roleName) {
        beforePropertyWrite("roleName", this.roleName, roleName);
        this.roleName = roleName;
    }

    public String getRoleName() {
        beforePropertyRead("roleName");
        return this.roleName;
    }

    public void addToDbstatuses(Dbstatus obj) {
        addToManyTarget("dbstatuses", obj, true);
    }

    public void removeFromDbstatuses(Dbstatus obj) {
        removeToManyTarget("dbstatuses", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Dbstatus> getDbstatuses() {
        return (List<Dbstatus>)readProperty("dbstatuses");
    }

    public void setFf(Formflow ff) {
        setToOneTarget("ff", ff, true);
    }

    public Formflow getFf() {
        return (Formflow)readProperty("ff");
    }

    public void addToStateTransitions(StateTransition obj) {
        addToManyTarget("stateTransitions", obj, true);
    }

    public void removeFromStateTransitions(StateTransition obj) {
        removeToManyTarget("stateTransitions", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<StateTransition> getStateTransitions() {
        return (List<StateTransition>)readProperty("stateTransitions");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "roleName":
                return this.roleName;
            case "dbstatuses":
                return this.dbstatuses;
            case "ff":
                return this.ff;
            case "stateTransitions":
                return this.stateTransitions;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "roleName":
                this.roleName = (String)val;
                break;
            case "dbstatuses":
                this.dbstatuses = val;
                break;
            case "ff":
                this.ff = val;
                break;
            case "stateTransitions":
                this.stateTransitions = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.roleName);
        out.writeObject(this.dbstatuses);
        out.writeObject(this.ff);
        out.writeObject(this.stateTransitions);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.roleName = (String)in.readObject();
        this.dbstatuses = in.readObject();
        this.ff = in.readObject();
        this.stateTransitions = in.readObject();
    }

}
